name: Docker Image CI

on:
  push:
    branches: [ "org_projects" ]
  pull_request:
    branches: [ "org_projects" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

    steps:
    - name: Checkout the code       
      uses: actions/checkout@v1   
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest 
        
    - name: Build and push the Docker image
      run: |
        docker buildx build --push --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:v1.18.0-org_projects --platform arm64 . 
